#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryViews.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ChangePassword.cshtml")]
    public class ChangePassword : System.Web.Mvc.WebViewPage<login.Models.ChangePasswordModel>
    {
        public ChangePassword()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "..\..\Views\Account\ChangePassword.cshtml"
  
    ViewBag.Title = "Canvi contrasenya";


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"formulari\">\r\n");


            
            #line 8 "..\..\Views\Account\ChangePassword.cshtml"
 using (Html.BeginForm()) {
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Account\ChangePassword.cshtml"
Write(Html.ValidationSummary());

            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Account\ChangePassword.cshtml"
                             


            
            #line default
            #line hidden
WriteLiteral(@"    <fieldset style=""width:99%;"">
        <legend>Canvi de contrasenya</legend>
        <div class=""fila"">
            <div class=""columna"" style=""width:300px;"">            
                    <div class=""cella"" style=""width:300px;"">
                        ");


            
            #line 16 "..\..\Views\Account\ChangePassword.cshtml"
                   Write(Html.Label("Contrasenya actual"));

            
            #line default
            #line hidden
WriteLiteral("                \r\n                        ");


            
            #line 17 "..\..\Views\Account\ChangePassword.cshtml"
                   Write(Html.PasswordFor(m => m.OldPassword));

            
            #line default
            #line hidden
WriteLiteral("                \r\n                    </div>\r\n                    <div class=\"cel" +
"la\" style=\"width:300px;\">\r\n                        ");


            
            #line 20 "..\..\Views\Account\ChangePassword.cshtml"
                   Write(Html.Label("Contrasenya nova"));

            
            #line default
            #line hidden
WriteLiteral("                \r\n                        ");


            
            #line 21 "..\..\Views\Account\ChangePassword.cshtml"
                   Write(Html.PasswordFor(m => m.NewPassword));

            
            #line default
            #line hidden
WriteLiteral("                \r\n                    </div>\r\n                    <div class=\"cel" +
"la\" style=\"width:300px;\">\r\n                        ");


            
            #line 24 "..\..\Views\Account\ChangePassword.cshtml"
                   Write(Html.Label("Confirmar contrasenya"));

            
            #line default
            #line hidden
WriteLiteral("                \r\n                        ");


            
            #line 25 "..\..\Views\Account\ChangePassword.cshtml"
                   Write(Html.PasswordFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral(@"                
                    </div>
            </div>
        </div>

        <div class=""fila"">
            <div class=""columna"">
                <div class=""buto"">    
                    <input type=""submit"" value=""Modificar"" />
                </div>
            </div>
        </div>
        
");


            
            #line 38 "..\..\Views\Account\ChangePassword.cshtml"
         if (ViewBag.Result!="")
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"fila\">\r\n                <div class=\"columna\">\r\n          " +
"          <div class=\"resultat\">\r\n                        <span>");


            
            #line 43 "..\..\Views\Account\ChangePassword.cshtml"
                         Write(ViewBag.Result);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n" +
"");


            
            #line 47 "..\..\Views\Account\ChangePassword.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </fieldset>\r\n");


            
            #line 49 "..\..\Views\Account\ChangePassword.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");


DefineSection("Scripts", () => {

WriteLiteral("\r\n    ");


            
            #line 54 "..\..\Views\Account\ChangePassword.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n");


DefineSection("Opcions", () => {

WriteLiteral("\r\n    <ul class=\"menuopt\">\r\n        <span>Opcions</span>\r\n        <li><a href=\"/l" +
"ogin/Account/Profile\">Modificar dades personals</a></li>\r\n        <li><a href=\"/" +
"login/Account/ChangePassword\">Canviar contrasenya</a></li>\r\n    </ul>\r\n");


});

WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
