#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryViews.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public class Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n    <head>\r\n        <meta charset=\"utf-8\" />\r\n" +
"        <title>");


            
            #line 5 "..\..\Views\Shared\_Layout.cshtml"
          Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - My ASP.NET MVC Application</title>\r\n        <link href=\"~/favicon.ico\" rel=\"sh" +
"ortcut icon\" type=\"image/x-icon\" />\r\n        <meta name=\"viewport\" content=\"widt" +
"h=device-width\" />\r\n        ");


            
            #line 8 "..\..\Views\Shared\_Layout.cshtml"
   Write(Styles.Render("~/Content/themes/base/css", "~/Content/css"));

            
            #line default
            #line hidden
WriteLiteral(" \r\n        ");


            
            #line 9 "..\..\Views\Shared\_Layout.cshtml"
   Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        \r\n        \r\n\r\n        \r\n    </head>\r\n    <body>\r\n\r\n    <div id=\"contain" +
"er\">\r\n        <div id=\"header\" >\r\n            <div id=\"siteinfo\">\r\n             " +
"   <div id=\"info\" >");


            
            #line 20 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Html.Partial("_LoginPartial"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n             </div>\r\n            <div id=\"mainnav\"  >\r\n                <d" +
"iv class=\"espais\"></div>\r\n                <div class=\"altre\" >\r\n                " +
"    ");


            
            #line 25 "..\..\Views\Shared\_Layout.cshtml"
               Write(Html.Partial("_MenuHor"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n\r\n        <div id=\"" +
"menuver\">\r\n            <div id=\"logo\"></div>\r\n            ");


            
            #line 32 "..\..\Views\Shared\_Layout.cshtml"
       Write(RenderSection("opcions", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div id=\"contents\">\r\n            ");


            
            #line 35 "..\..\Views\Shared\_Layout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div id=\"footer\"></div>\r\n    </div>\r\n    ");


            
            #line 40 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
