#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryViews.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_LoginPartial.cshtml")]
    public class LoginPartial : System.Web.Mvc.WebViewPage<dynamic>
    {
        public LoginPartial()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Shared\_LoginPartial.cshtml"
 if (Request.IsAuthenticated) {

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        <a href=\"/login/Account/LogOff\" class=\"logoff\"><span>Desconectar" +
"</span> </a>\r\n        <a href=\"/login/Account/Profile\" class=\"profile\"><span>Dad" +
"es personals</span> </a>\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        Usuari: ");


            
            #line 7 "..\..\Views\Shared\_LoginPartial.cshtml"
           Write(Html.Label(User.Identity.Name));

            
            #line default
            #line hidden
WriteLiteral("    \r\n    </p>\r\n");


            
            #line 9 "..\..\Views\Shared\_LoginPartial.cshtml"
 
}
            
            #line default
            #line hidden
WriteLiteral(" ");


        }
    }
}
#pragma warning restore 1591
