#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryViews.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.4.1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_MenuHor.cshtml")]
    public class MenuHor : System.Web.Mvc.WebViewPage<dynamic>
    {
        public MenuHor()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Shared\_MenuHor.cshtml"
 if (Request.IsAuthenticated)
{


            
            #line default
            #line hidden
WriteLiteral("                   <!-- MyCSSMenu Structure [Menu 0] -->\r\n");


            
            #line 5 "..\..\Views\Shared\_MenuHor.cshtml"


            
            #line default
            #line hidden
WriteLiteral(@"                    <ul id=""qm0"" class=""qmmc"">

	                    <li><a  href=""javascript:void(0)"">CONFIGURACIÓ</a>

		                    <ul>
		                    <li><span class=""qmtitle"" >Seguretat</span></li>
		                    <li><a href=""http://localhost/Guestbook"">Usuaris</a></li>
                            <li><a href=""javascript:void(0)"">Aplicacions</a></li>
    	                    <li><a href=""javascript:void(0)"">Rols</a></li>
		                    </ul>
                        </li>

	                    <li><span class=""qmdivider qmdividery"" ></span></li>
	                    <li><a class=""qmparent"" href=""javascript:void(0)"">GESTIÓ TRIBUTÀRIA</a>

		                    <ul>
		                    <li><span class=""qmtitle"" >Impostos</span></li>
                            <li><a href=""javascript:void(0)"">IBI</a></li>
		                    <li><a href=""javascript:void(0)"">IVTM</a></li>
		                    <li><a href=""javascript:void(0)"">IAE</a></li>
		                    <li><a href=""javascript:void(0)"">ICIO</a></li>
		                    <li><span class=""qmdivider qmdividerx"" ></span></li>
		                    <li><span class=""qmtitle"" >Taxes</span></li>
                            <li><a href=""javascript:void(0)"">Escombraries</a></li>
		                    <li><a href=""javascript:void(0)"">Guals</a></li>
		                    </ul>
                         </li>


                    <li class=""qmclear"">&nbsp;</li></ul>
");


            
            #line 36 "..\..\Views\Shared\_MenuHor.cshtml"


}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
